### ISSUE TITLE
Sorry, Unable to process request at this time -- error 999

### ISSUE THREAD

**Issue by dennislwy** [lppkarl/YahooFinanceApi#23]
Yahoo seems terminated their free api service

Flurl.Http.FlurlHttpException occurred
  HResult=0x80131500
  Message=GET https://download.finance.yahoo.com/d/quotes.csv?s=AAPL%2BGOOG&f=l1ohgp failed with status code 999 (Request denied).
Response body:
<html><head><title>Yahoo! - 999 Unable to process request at this time -- error 999</title></head><body>Sorry, Unable to process request at this time -- error 999.</body></html>
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Flurl.Http.FlurlRequest.<SendAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Flurl.Http.FlurlRequest.<SendAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Flurl.Http.FlurlRequest.<SendAsync>d__18.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Flurl.Http.HttpResponseMessageExtensions.<ReceiveStream>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YahooFinanceApi.Yahoo.Builder.<GetAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WindowsFormsApp1.Form1.<button1_Click>d__2.MoveNext() in d:\temp\WindowsFormsApp1\WindowsFormsApp1\Form1.cs:line 27

**Comment by dotnetshadow** [comment]
@dennislwy I can confirm that I'm also getting this issue, hopefully there is a way around this

**Comment by ntrous** [comment]
I'm also getting the issue

**Comment by delvier** [comment]
yahoo coment with:
"It has come to our attention that this service is being used in violation of the Yahoo Terms of Service. As such, the service is being discontinued. For all future markets and equities data research, please refer to finance.yahoo.com."

**Comment by delvier** [comment]
@dennislwy What query type you call to produce this GET URI  ?

I checked the historical api, and the URI generated for a call is like that:

https://query1.finance.yahoo.com/v7/finance/download/JUNO?period1=1488949200&period2=1490673600&interval=1d&events=history&crumb=j1WuKmwg9Nz

And this endpoint works perfectly fine.

**Comment by lppkarl** [comment]
@dennislwy Thanks for your notice! It seems Yahoo has changed the mechanism again, I need some time to find a solution of it. If anyone has any fix or discovered something, please also comment here 😄

**Comment by dshe** [comment]
This url seems to work:
https://query1.finance.yahoo.com/v7/finance/quote?symbols=AAPL

**Comment by mayerwin** [comment]
@lppkarl have you planned to use https://query1.finance.yahoo.com/v7/finance/quote?symbols=AAPL to fix the issue? I personally just need the last price (delayed is OK).

You can upvote this suggestion to implement api keys to address Yahoo's concerns: https://yahoo.uservoice.com/forums/382977-finance/suggestions/32214556-reinstate-the-stock-quote-api-using-unique-keys
The other thread has been closed by Yahoo, with a rather laughable explanation.

**Comment by lppkarl** [comment]
@mayerwin, @dshe has completed the task 👍  and I have pushed the new version to nuget as a beta version. The QueryTag will be implemented later for ease to get the quote properties 😄
